site_name: TiltSense - Documentation
site_url: https://bananabrewery.github.io/TiltSense
repo_url: https://github.com/bananabrewery/TiltSense
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  font:
    text: Alexandria Thin
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      background: "#f8f9fa"
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      background: "#212529"
  custom_dir: overrides
  features:
    - navigation.footer
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bananabrewery
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/bananabrewery
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/bananabrewery
    - icon: fontawesome/brands/tiktok
      link: https://tiktok.com/@bananabrewery
    - icon: fontawesome/brands/twitter
      link: https://x.com/BananaBrewery
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@BananaBrewery
extra_css:
  - stylesheets/colors.css
plugins:
  - search
  - i18n:
        docs_structure: folder
        languages:
          - locale: en
            default: true
            name: English
            build: true
          - locale: es
            name: Spanish
            build: true
nav:
  - Home: index.md
  - What is TiltSense?: index.md
  - Hardware Requirements: Hardware.md
  - Assembly Instructions: Assembly.md
  - Firmware Configuration and Installation: Firmware-Setup.md
  - Device Usage and Features: Usage.md
  - Development and Contributions: Development.md
  - Frequently Asked Questions (FAQ): FAQ.md
  - Credits and Acknowledgements: Credits.md